---
whitelist:
#- MIT
#- Apache 2.0
ignore_groups:
#- test
#- development
ignore_dependencies:
#- bundler
dependencies_file_dir: './doc/'
project_name: # project name
gradle_command: # only meaningful if used with a Java/gradle project. Defaults to "gradle".
